apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  selector:
    app: my-java-app  # Should match the label in your deployment.yml
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # The port your app is listening on inside the container
  type: LoadBalancer  # Makes your service accessible externally
