name: Build and Deploy to AKS

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t my-java-app .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Tag and push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-java-app:latest ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest

      # Deploy to Azure Kubernetes Service (AKS)
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          kubeconfig: ${{ secrets.AZURE_K8S_KUBECONFIG }}
          namespace: default
          manifests: |
            kubernetes/deployment.yml
            kubernetes/service.yml
